name: changeset release

on:
  workflow_call:
jobs:
  changeset:
    name: Create or deploy changeset release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
